name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      # Install & cache dependencies for Backend
      - name: Use Node.js ${{ matrix.node-version }} (Backend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json # Specify the backend lock file

      - name: Install dependencies (Backend)
        working-directory: backend
        run: npm ci

      - name: Build Backend
        working-directory: backend
        run: npm run build --if-present

      - name: Test Backend
        working-directory: backend
        run: npm test

      # Install & cache dependencies for Frontend
      - name: Use Node.js ${{ matrix.node-version }} (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json # Specify the frontend lock file

      - name: Install dependencies (Frontend)
        working-directory: frontend
        run: npm ci

      - name: Build Frontend
        working-directory: frontend
        run: npm run build --if-present

      - name: Test Frontend
        working-directory: frontend
        run: npm test
